In [1]:
import numpy as np 

# Gradientti 

In [2]:
x,y,z = np.mgrid[0:20:1, 0:20:1, 0:20:1]

V = 2*x**2 + 3*y**2 - 4*z # just a random function for the potential

Ex,Ey,Ez = np.gradient(V)

In [3]:
Ex[0,0,0], Ey[0,0,0], Ez[0,0,0]

(2.0, 3.0, -4.0)

In [4]:
Ex[1, 2, 3], Ey[1, 2, 3], Ez[1, 2, 3]

(4.0, 12.0, -4.0)

In [5]:
x, y = np.mgrid[0:21, 0:21]

f = x**2*y 

Dfx, Dfy = np.gradient(f)

In [20]:
Dfx[3], Dfy[2]

(array([  0.,   6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.,  60.,
         66.,  72.,  78.,  84.,  90.,  96., 102., 108., 114., 120.]),
 array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
        4., 4., 4., 4.]))

In [21]:
Dfx[3, 2], Dfy[3, 2]

(12.0, 9.0)

In [20]:
len(np.gradient(f))

2

# Derivaatta 

In [38]:
x = np.arange(0,21)
g = x**2 
g


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [34]:
dgdx = np.gradient(g, 1)
dgdx

array([ 1.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 39.])

In [35]:
len(dgdx)

21

Accurate values: 

In [39]:
accurate = [2*s for s in range(0,21)]
accurate

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]

In [37]:
len(accurate)

20

# Laplacian 


In [22]:
Dfx.shape, Dfy.shape 

((21, 21), (21, 21))

In [31]:
laplacian_f= np.gradient(Dfx)[0]+ np.gradient(Dfy)[1]
laplacian_f

array([[ 0. ,  1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ,
        11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 20. ],
       [ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
        16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. , 28.5, 30. ],
       [ 0. ,  2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ,
        22. , 24. , 26. , 28. , 30. , 32. , 34. , 36. , 38. , 40. ],
       [ 0. ,  2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ,
        22. , 24. , 26. , 28. , 30. , 32. , 34. , 36. , 38. , 40. ],
       [ 0. ,  2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ,
        22. , 24. , 26. , 28. , 30. , 32. , 34. , 36. , 38. , 40. ],
       [ 0. ,  2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ,
        22. , 24. , 26. , 28. , 30. , 32. , 34. , 36. , 38. , 40. ],
       [ 0. ,  2. ,  4. ,  6. ,  8. , 10. , 12. , 14. , 16. , 18. , 20. ,
        22. , 24. , 26. , 28. , 30. , 32. , 34. , 36. , 38. , 40. ],

In [32]:
laplacian_f.shape 

(21, 21)

In [46]:
laplacian_f[3,20]

40.0

### Laplacian 3d 

In [7]:
x,y,z = np.mgrid[0:20:1, 0:20:1, 0:20:1]

V = 2*x**2 + 3*y**2 - 4*z # just a random function for the potential

Ex,Ey,Ez = np.gradient(V)

In [9]:
Ex[0,0,0], Ey[0,0,0], Ez[0,0,0]

(2.0, 3.0, -4.0)

In [10]:
Ex[1, 2, 3], Ey[1, 2, 3], Ez[1, 2, 3]

(4.0, 12.0, -4.0)

In [22]:
laplacian_V = np.gradient(Ex)[0]+ np.gradient(Ey)[1] + np.gradient(Ez)[2]
laplacian_V


array([[[ 5. ,  5. ,  5. , ...,  5. ,  5. ,  5. ],
        [ 6.5,  6.5,  6.5, ...,  6.5,  6.5,  6.5],
        [ 8. ,  8. ,  8. , ...,  8. ,  8. ,  8. ],
        ...,
        [ 8. ,  8. ,  8. , ...,  8. ,  8. ,  8. ],
        [ 6.5,  6.5,  6.5, ...,  6.5,  6.5,  6.5],
        [ 5. ,  5. ,  5. , ...,  5. ,  5. ,  5. ]],

       [[ 6. ,  6. ,  6. , ...,  6. ,  6. ,  6. ],
        [ 7.5,  7.5,  7.5, ...,  7.5,  7.5,  7.5],
        [ 9. ,  9. ,  9. , ...,  9. ,  9. ,  9. ],
        ...,
        [ 9. ,  9. ,  9. , ...,  9. ,  9. ,  9. ],
        [ 7.5,  7.5,  7.5, ...,  7.5,  7.5,  7.5],
        [ 6. ,  6. ,  6. , ...,  6. ,  6. ,  6. ]],

       [[ 7. ,  7. ,  7. , ...,  7. ,  7. ,  7. ],
        [ 8.5,  8.5,  8.5, ...,  8.5,  8.5,  8.5],
        [10. , 10. , 10. , ..., 10. , 10. , 10. ],
        ...,
        [10. , 10. , 10. , ..., 10. , 10. , 10. ],
        [ 8.5,  8.5,  8.5, ...,  8.5,  8.5,  8.5],
        [ 7. ,  7. ,  7. , ...,  7. ,  7. ,  7. ]],

       ...,

       [[ 7. ,  7. ,  7.

In [25]:
laplacian_V[10,10,10]

10.0